name: ddpm-lucidrains
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
    #  - pytorch=1.11.0
    #  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - accelerate
    - einops==0.7.0
    - ema-pytorch>=0.4.2
    - pillow
    - pytorch-fid
    - torch==2.0.0
    - torchvision
    - torchinfo
